env:
  es6: true
  node: true
  mocha: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
  ecmaVersion: 8
  ecmaFeatures:
    experimentalObjectRestSpread: true
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-unused-vars:
    - error
    - argsIgnorePattern: next
  no-trailing-spaces:
    - error
  object-curly-spacing:
    - error
    - always
  space-infix-ops:
    - error
  space-before-blocks:
    - error
  key-spacing:
    - error
    - {afterColon: true}
  comma-spacing:
    - error
    - {before: false, after: true}
  no-multiple-empty-lines:
    - error
    - {max: 1, maxEOF: 1}
  comma-dangle:
    - error
    - always-multiline
  eol-last:
    - error
    - always
  no-multi-spaces:
    - error
