version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.8.1
        environment:
          PGHOST: 127.0.0.1
          PGUSER: user
          NODE_ENV: test
          JWT_SECRET: SuPeRsEcReTy
          TEST_DATABASE_URL: postgres://localhost/letsbook_test
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: letsbook_test

    working_directory: ~/letsbook-server

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Set up DB
          command:
            yarn db:migrate:test
          environment:
            TEST_DATABASE_URL: postgres://user@localhost:5432/letsbook_test
      - run: sudo mkdir -p $CIRCLE_TEST_REPORTS/phpunit
      - run: yarn lint; yarn coverage; yarn report;
      - run: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - $HEROKU_SSH_FINGERPRINT
      - deploy:
          name: Deploy to Heroku if tests pass and branch is master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git push --force git@heroku.com:$HEROKU_APP_NAME.git HEAD:refs/heads/master
            fi
